// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://meitoqhuhwqhzjywbxyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1laXRvcWh1aHdxaHpqeXdieHlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1ODc2NTksImV4cCI6MjA2MjE2MzY1OX0.pmTYmg50t1r4Vmk2y_MWDCzz2-5hVgJfHonQUDG4HwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);